### ISSUE TITLE
Support HSTORE

### ISSUE THREAD

**Issue by tblundy** [sfu-db/connector-x#174]
Currently reading from a postgres database that has data in hstore format, I get 
`PanicException: not implemented: hstore`

Hstore is a key-value format, similar to jsonb. [https://www.postgresql.org/docs/14/hstore.html](https://www.postgresql.org/docs/14/hstore.html)
Supporting it could be a worthwhile addition. It could be parsed into a dictionary or passed through as a string.

**Comment by wangxiaoying** [comment]
Hi @tblundy , thanks for the suggestion! We will add it to our plan for next release (after 0.2.2).

**Comment by wangxiaoying** [comment]
Hi, we have add the support for HSTORE (convert to string) in 0.2.3 release. However since the underlying's driver does not support this type in `copy_out`, we can only support this in the `cursor` protocol. For `binary` and `csv` protocol, a workaround is to convert the HSTORE column to string directly in the sql query.
