### ISSUE TITLE
Publish 0.3 to creates.io

### ISSUE THREAD

**Issue by houqp** [sfu-db/connector-x#290]
#### Describe your feature request

Hi, could you publish 0.3 to crates.io so it can be consumed from downstream crates? Thanks!

**Comment by wangxiaoying** [comment]
Hi @houqp , thanks for the PRs. Can you try out: https://crates.io/crates/connectorx/0.3.1-alpha.1 ?

**Comment by wangxiaoying** [comment]
In order to publish to crates.io, I need to change the `datafusion` dependency: https://github.com/sfu-db/connector-x/commit/1bc46cf23bf7b980b51eb811577b5709b0d413d1. I'm suspecting this is the reason that cause the CI for federated query failing: https://github.com/sfu-db/connector-x/runs/6649877888?check_suite_focus=true#step:13:595

**Comment by houqp** [comment]
Thanks, works alpha.1 works for me!
