### ISSUE TITLE
Reading SQLite DATETIME Column With TEXT Values Shows RuntimeError

### ISSUE THREAD

**Issue by d33bs** [sfu-db/connector-x#306]
#### What language are you using?

Python

#### What version are you using?

Python 3.9, connectorx==0.3.0

#### What database are you using?

SQLite

#### What dataframe are you using?

Arrow, Pandas

#### Can you describe your bug?

SQLite table DATETIME column with TEXT values results in errors similar to the below:

`RuntimeError: Conversion error from type Text at index: <column index>, trailing input`

#### What are the steps to reproduce the behavior?

See below

##### Database setup if the error only happens on specific data or data type

SQLite DATETIME columns with TEXT values.

##### Example query / code

```python
import tempfile

import connectorx as cx
from sqlalchemy import create_engine

# create temp database path
tmpdir = tempfile.gettempdir()
sql_path = f"sqlite:///{tmpdir}/test_sqlite.sqlite"

# create sqlalchemy engine from path
engine = create_engine(sql_path)

with engine.begin() as connection:
    # drop if exists and create example table with DATETIME column
    connection.execute("DROP TABLE IF EXISTS example;")
    connection.execute("CREATE TABLE example (RandomDate DATETIME);")

    # insert a TEXT value into the example table DATETIME column
    connection.execute(
        "INSERT INTO example VALUES (?);",
        ["123-123"],
    )

# select the data using connectorx
cx.read_sql(
    conn=sql_path,
    query="select * from example;",
    return_type="pandas", # doesn't seem to matter which return type specified here
)
```

#### What is the error?

`RuntimeError: Conversion error from type Text at index: 0, input contains invalid characters`

**Comment by wangxiaoying** [comment]
Hi @d33bs , Internally connectorx would choose to use your defined data type in SQLite which is `DATETIME`, so it will try to parse your `TEXT` string into a `NaiveDateTime` type in Rust. It seems like the error is caused by your value "123-123", which is not a valid DateTime string. Can you try a valid text like '2007-01-01 10:00:19' to see whether it works? If you have to have this invalid text in the column, maybe it is more appropriate to define `TEXT` instead of `DATETIME`?

**Comment by d33bs** [comment]
Thank you @wangxiaoying ! I tried using the example datetime you provided and this does appear to successfully query the data.

A more realistic entry where I'm seeing this issue occur would be '2013-03-12T08:00:03.623-04:00'. This example does cause the issue to occur in the same way that '123-123' does. Are there any workarounds you'd suggest to get around this without reformatting the data itself before read by connector-x?

**Comment by wangxiaoying** [comment]
Hi @d33bs , currently we cannot support arbitrary datetime format since the underlying client driver [rusqlite](https://docs.rs/rusqlite/latest/rusqlite/index.html#) we use kind of hard coded the datetime format like [here](https://docs.rs/rusqlite/latest/src/rusqlite/types/chrono.rs.html#69-84). Therefore, for workaround I think maybe one way is to  reformat the data when you select it like [this example](https://learnsql.com/cookbook/how-to-format-a-datetime-in-sqlite/), or to define the column as `TEXT` and convert it to datetime after getting the dataframe from connectorx.

**Comment by d33bs** [comment]
Thanks @wangxiaoying , this makes the challenges clearer, really appreciate the further clarification. If it doesn't already exist, would you be open to documentation additions to clarify this constraint for others who may run into the same question?

**Comment by wangxiaoying** [comment]
Thank you @d33bs , that's a great suggestion! I will definitely put this in the document.
